---
title: "Quandl Examples"
author: "Albert Y. Kim"
date: April 10, 2015
output: html_document
---

If you create an account, you can obtain an authorization token to make more than 50 calls in one day at [https://www.quandl.com/account](https://www.quandl.com/account)

```{r, message=FALSE, warning=FALSE}
library(Quandl)
# Quandl.auth("ENTER_AUTH_CODE_HERE")
Quandl.auth("izVwTt9m5VoEe7TsEzdr")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(ggthemes))
suppressPackageStartupMessages(library(scales))
```


```{r, message=FALSE, warning=FALSE}
# Download data
US.fertility <-  Quandl("WORLDBANK/USA_SP_DYN_TFRT_IN")
head(US.fertility)
plot(as.Date(US.fertility$Date), US.fertility$Value, type='l', xlab="Date", 
     ylab="Fertility Rate", main="US Fertility Rate")
```





### Comparing the Price of Gold to the Price of Bitcoin

```{r, message=FALSE, warning=FALSE}
bitcoin <- Quandl("BAVERAGE/USD", start_date="2013-01-01")
bitcoin %>% tbl_df()
gold <- Quandl("BUNDESBANK/BBK01_WT5511", start_date="2013-01-01")
gold %>% tbl_df()
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Get bitcoin differences
bitcoin <- bitcoin %>% 
  mutate(Date=ymd(Date)) %>%
  rename(price = `24h Average`) %>% 
  select(Date, price) %>%
  arrange(Date) %>% 
  mutate(
    lag.price = lag(price),
    rel.diff = (price-lag.price)/lag.price,
    type = "Bitcoin"
    ) %>%
  select(Date, rel.diff, type)

# Get gold differences
gold <- gold %>% 
  mutate(Date=ymd(Date)) %>%
  rename(price=Value) %>% 
  arrange(Date) %>% 
  mutate(
    lag.price = lag(price),
    rel.diff = (price-lag.price)/lag.price,
    type = "Gold"
    ) %>%
  select(Date, rel.diff, type)

# Combine the two since they have the same columns and plot
combined <- bind_rows(bitcoin, gold)
ggplot(data=combined, aes(x=Date, y=rel.diff, col=type)) + 
  geom_line() + 
  scale_y_continuous(labels = percent) + 
  ylab("Day-Over-Day Relative % Change") + 
  ggtitle("Volatility of Bitcoin and Gold Prices")
```





### Comparing Milk and Cheese Production in the US

By Rachel Fox

```{r, echo=FALSE, message=FALSE, warning=FALSE}
cheese <- Quandl("USDANASS/NASS_CHEESEPRODUCTIONMEASUREDINLB")
milk <-  Quandl("USDANASS/NASS_MILKPRODUCTIONMEASUREDINLB")
cheese.date <- interval(ymd(19241231), ymd(20131231))

cheese <- filter(cheese, Date %within% cheese.date) %>%
  mutate(type = "cheese")
milk <- filter(milk, Date %within% cheese.date) %>%
  mutate(type = "milk")

milk.cheese <- bind_rows(milk, cheese)

ggplot(data=milk.cheese, aes(x=Date, y=Value, color=type)) +
  geom_line() +
  theme_economist()+
  theme(plot.title=element_text(size=10))+
  scale_y_log10()+
  xlab("Date") + ylab("Pounds (lbs) of Cheese and Milk Produced (log-scale)") +
  ggtitle("Production of Cheese and Milk in the US from 1924 to 2013")
```





### Portland, OR Median House Prices

By Liam Bowcock (source Zillow).

```{r, echo=FALSE, warning=FALSE, message=FALSE}
sale.price <- Quandl("ZILLOW/MMETRO_MEDIANSOLDPRICE_ALLHOMES_PORTLANDOR", trim_start="2008-11-12") %>% rename(sale.price = `Value`)

ggplot(sale.price, aes(x = Date, y = sale.price)) +
  geom_point() +
  geom_smooth() +
  ylab("Median Sale Price (USD)") +
  ggtitle("Portland Metro Area Monthly Median House Sale Price")
```





### Apple Stock

By Dean Young

```{r, echo=FALSE, warning=FALSE, message=FALSE}
aapl <- Quandl("GOOG/NASDAQ_AAPL") %>% tbl_df()
aapl <- select(aapl,Date,Close)
aapl$Date <- ymd(aapl$Date)

ggplot(data=aapl, aes(x=Date,y=Close)) + geom_line() + geom_smooth(size=1.5, col="red") +
  xlab("Time") + ylab("Closing Price (USD)") + ggtitle("aapl")
```